name: qmmm
channels:
    - psi4/label/dev
    - psi4
    - anaconda
dependencies:
    - python=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - sympy
    - IPython
    - jupyter
    - pip:
        - pyscf
    - psi4
    - cmake
    - cython
